### ISSUE TITLE
not building correctly on readthedocs

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stsci_rtd_theme#1]
@sosey, has anyone built this successfully on readthedocs? @jhunkeler  and I couldn't get it to work.  It builds fine when I do a local sphinx run, but when readthedocs builds non of the style/theme stuff is there, just a bunch of plain html.  Joe and I were looking at the JWST repo that's using it and he said they're not actually building the docs on readthedocs.  Might be easier to chat in person, but thought I'd throw it on here so I wasn't ambushing you.

BTW, I was attempting this for stak-notebooks

**Comment by sosey** [comment]
No - I didn't add the RTD specs but can, I have it on wfc3tools.
