### ISSUE TITLE
Sphinx 3.0 deprecation for <script>

### ISSUE THREAD

**Issue by sosey** [spacetelescope/stsci_rtd_theme#11]
This warning was encountered during documentation build for the jwst package. Look into any necessary changes that need to be made to this theme.

> writing additional pages... search/miniconda3/envs/jwstdev/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
>   {{ super() }}

**Comment by pllim** [comment]
Hmm. I didn't see this with Sphinx 3.0.2. Is this still an issue?

**Comment by sosey** [comment]
closing, I dont think it's relevant anymore
