### ISSUE TITLE
Bullet characters not rendering

### ISSUE THREAD

**Issue by ojustino** [spacetelescope/stsci_rtd_theme#19]
Hi, I am working on documentation in Sphinx for `STScI-STIPS` that uses `stsci_rtd_theme`. I have noticed that the bullet character doesn't render in outer lists for us, and the same is the case [in the `jwst` docs](https://jwst-pipeline.readthedocs.io/en/latest/jwst/introduction.html#output-file) (which also use this theme).

I don't have this problem when I switch to `sphinx_rtd_theme`, though I found that they had to [fix this same problem](https://github.com/readthedocs/sphinx_rtd_theme/issues/1115) with bullet characters last year. Might the fix for `stsci_rtd_theme` look similar to theirs?

For more context, outer bulleted lists seem like the only problem case. Numbered lists seem OK, and bullets do render properly when they are inside a numbered list, like the following:
```
#. You will need to clone the STIPS source code from the
   `spacetelescope/STScI-STIPS <https://github.com/spacetelescope/STScI-STIPS.git>`_
   repository. ``cd`` into the directory where you would like to store the
   source code and run::

        git clone https://github.com/spacetelescope/STScI-STIPS.git

        cd STScI-STIPS

#. The environment file can be used in two ways:

   * To create a new Conda environment named ``stips``::

        conda env create -f environment.yml
        conda activate stips


   * Or, to install to or update an existing and currently active Conda environment::

        conda env update --file environment.yml
```

**Comment by sosey** [comment]
It's likely that the fix involves making similar edits in the css file that we use in this theme - that's here:

https://github.com/spacetelescope/stsci_rtd_theme/blob/master/stsci_rtd_theme/static/stsci.css

If you wanna take a crack at making the update on your local fork,  you can submit back a PR :)

**Comment by ojustino** [comment]
I did in #20. Is anyone slated to respond?
