### ISSUE TITLE
is an updated release of stsci_rtd_theme possible?

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/stsci_rtd_theme#27]
Hi, I see there hasn't been any release of `stsci_rtd_theme` since June 2022. There were several PRs with fixes merged into this back in October 2022, but there hasn't been any release since then. 

Is there a chance an updated release including those fixes might be possible?  I'd really like to be able to use the fix to the rendering of bulleted lists in the readthedocs for webbpsf, but right now that's not easily possible. 

Alternatively, if this isn't being actively supported any more, is there a different recommended package for theming RTD docs consistently? Thanks. 

(I'm guessing this might be a question for @nden or @sosey, based on who did the prior releases of this a while ago. Thanks much for any help or guidance. :-)

**Comment by nden** [comment]
@mperrin We'll make a release in the next few days.

**Comment by mperrin** [comment]
Super, thanks so much! Very much appreciated.

**Comment by zacharyburnett** [comment]
released with version `1.0.1`
