### ISSUE TITLE
Pygments can't find "basic" theme

### ISSUE THREAD

**Issue by sean-lockwood** [spacetelescope/stsci_rtd_theme#6]
Sphinx builds with this package are failing to build my docs because it can't find the "basic" style in Pygments:
`pygments.util.ClassNotFound: Could not find style module 'basic'.`

I changed the `theme.conf` file to specify `pygments_style = default` theme for inheritance in my local instance and it worked.  Does this give similar results?

**Comment by sosey** [comment]
@sean-lockwood I don't have the same problem, but I was running  sphinx_rtd_theme v0.2.4, which is fairly old. This theme inherits from `sphinx_rtd_theme` and the most recent `sphinx_rtd_theme` has changed the pygments style to default, though it looks like basic still exists.  RTD has updated to a later version of `sphinx_rtd_theme`  as well it appears: https://github.com/rtfd/readthedocs.org/pull/4096.  Referencing this discussion as well: https://github.com/rtfd/readthedocs.org/issues/4050#issuecomment-386410450

The pygments style is used for highlights, when I checked locally changing from basic to default removed the alternate row highlighting on tables when using the following versions:

> sphinx-automodapi         0.8                       <pip>
> sphinx-rtd-theme          0.4.2                     <pip>
> sphinxcontrib-websupport  1.1.0                <pip>


Let me look around to see what the best update might be....in the meantime, could you post the versions of the same package that you have installed?

thanks!

**Comment by sean-lockwood** [comment]
`sphinx-automodapi`:  Not installed
`sphinx_rtd_theme`:  Tried with both `0.4.2` (latest on conda) and `0.1.9` (astroconda channel)
`sphinxcontrib-websupport`:  `1.0.1`

**Comment by sosey** [comment]
thanks. What did seem to work well for me, i.e. gave me expected result,  was updating the theme to use default, and specifying default in the project conf for pygments_style.

**Comment by sosey** [comment]
fixed applied in https://github.com/spacetelescope/stsci_rtd_theme/releases/tag/0.0.2
